export const CHAT_PAGE = String.raw`<!doctype html>
<html lang="vi">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>Workflow AI</title>
  <style>
    :root{font-family:Inter,Segoe UI,Arial,sans-serif;color:#172033;background:#eef2f7;line-height:1.45}
    *{box-sizing:border-box}body{margin:0;height:100vh;overflow:hidden}button,textarea,input{font:inherit}
    button{border:0;border-radius:10px;padding:10px 14px;cursor:pointer;font-weight:700;background:#2563eb;color:white}
    button.ghost{background:#eef2f7;color:#344054}button.success{background:#067647}button.danger{background:#b42318}button:disabled{opacity:.55;cursor:not-allowed}
    .shell{display:grid;grid-template-columns:300px 1fr;height:100vh}.side{background:#101828;color:#fff;padding:16px;display:flex;flex-direction:column;gap:14px;min-width:0}
    .brand{display:flex;align-items:center;justify-content:space-between;gap:10px}.brand h1{font-size:18px;margin:0}.brand small{color:#b8c2d8;display:block}.side button{width:100%}
    .conversations{overflow:auto;display:flex;flex-direction:column;gap:7px}.conversation{padding:10px;border-radius:10px;background:#ffffff0c;border:1px solid #ffffff14;cursor:pointer}.conversation.active{background:#2563eb;border-color:#60a5fa}.conversation b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.conversation span{font-size:12px;color:#cbd5e1;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    .side-foot{margin-top:auto;font-size:12px;color:#b8c2d8}.main{display:flex;flex-direction:column;min-width:0;height:100vh}.top{height:64px;background:#fff;border-bottom:1px solid #dfe5ef;display:flex;align-items:center;justify-content:space-between;padding:0 20px;gap:14px}.top-title{min-width:0}.top-title b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.top-title span{font-size:12px;color:#667085}.badge{display:inline-flex;align-items:center;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:800;background:#eef2f7;color:#344054}.badge.ok{background:#dcfae6;color:#067647}.badge.warn{background:#fef0c7;color:#b54708}.badge.bad{background:#fee4e2;color:#b42318}
    .content{flex:1;overflow:auto;padding:22px}.thread{max-width:920px;margin:0 auto;display:flex;flex-direction:column;gap:14px}.empty{background:#fff;border:1px solid #dfe5ef;border-radius:16px;padding:28px;text-align:center;color:#475467}.bubble{max-width:82%;border-radius:16px;padding:13px 15px;white-space:pre-wrap;word-break:break-word;box-shadow:0 3px 12px #1018280b}.bubble.user{align-self:flex-end;background:#2563eb;color:#fff;border-bottom-right-radius:5px}.bubble.assistant{align-self:flex-start;background:#fff;border:1px solid #dfe5ef;border-bottom-left-radius:5px}.bubble .meta{font-size:11px;opacity:.72;margin-top:7px}
    .card{background:#fff;border:1px solid #dfe5ef;border-radius:14px;padding:14px;box-shadow:0 3px 12px #1018280b}.card h3{font-size:14px;margin:0 0 8px}.progress{border-left:4px solid #60a5fa}.approval{border-left:4px solid #f59e0b}.clarification{border-left:4px solid #8b5cf6}.diagnostic{border-left:4px solid #ef4444}.muted{color:#667085;font-size:13px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.options{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.option{background:#f3e8ff;color:#6b21a8}.detail{margin-top:10px}pre{white-space:pre-wrap;word-break:break-word;background:#101828;color:#d0d5dd;padding:12px;border-radius:10px;max-height:320px;overflow:auto;font-size:12px}
    .composer-wrap{background:#fff;border-top:1px solid #dfe5ef;padding:14px 20px}.composer{max-width:920px;margin:0 auto;border:1px solid #cbd5e1;border-radius:16px;padding:10px;background:#fff;box-shadow:0 6px 20px #10182812}.composer.drag{outline:3px solid #93c5fd}.attachments{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:7px}.file-chip{background:#eff6ff;color:#1d4ed8;border-radius:999px;padding:5px 9px;font-size:12px}.input-row{display:flex;gap:9px;align-items:flex-end}.input-row textarea{flex:1;border:0;outline:0;resize:none;min-height:50px;max-height:180px;padding:8px}.icon{background:#eef2f7;color:#344054;flex:0 0 auto}.send{flex:0 0 auto}.hint{max-width:920px;margin:7px auto 0;font-size:12px;color:#667085;text-align:center}.startup{position:fixed;inset:0;background:#f3f6fb;display:flex;align-items:center;justify-content:center;padding:20px;z-index:50}.startup-card{width:min(560px,100%);background:#fff;border:1px solid #dfe5ef;border-radius:18px;padding:24px;box-shadow:0 12px 40px #1018281a}.hidden{display:none!important}
    @media(max-width:800px){.shell{grid-template-columns:1fr}.side{position:fixed;inset:0 25% 0 0;z-index:30;transform:translateX(-105%);transition:.2s}.side.open{transform:translateX(0)}.mobile-menu{display:inline-flex!important}.bubble{max-width:94%}.content{padding:14px}.composer-wrap{padding:10px}.top{padding:0 12px}}
    .mobile-menu{display:none}
  </style>
</head>
<body>
<div id="startup" class="startup"><div class="startup-card"><h2 id="startupTitle">Đang khởi động Workflow AI</h2><p id="startupMessage" class="muted">Đang kiểm tra mô hình cục bộ và các dịch vụ cần thiết.</p><div class="actions"><button id="retryStartup" class="hidden">Thử lại</button><button id="copyStartup" class="ghost hidden">Sao chép lỗi để hỏi ChatGPT</button></div></div></div>
<div class="shell">
  <aside id="side" class="side">
    <div class="brand"><div><h1>Workflow AI</h1><small>Chat-first · V1_ONLY</small></div></div>
    <button id="newConversation">+ Cuộc trò chuyện mới</button>
    <div id="conversationList" class="conversations"></div>
    <div class="side-foot"><div id="modelState">Mô hình: đang kiểm tra</div><div>API trả phí: 0 USD</div><div><a href="/admin" target="_blank" style="color:#93c5fd">Khu vực kỹ thuật</a></div></div>
  </aside>
  <main class="main">
    <header class="top"><button id="menu" class="ghost mobile-menu">☰</button><div class="top-title"><b id="currentTitle">Cuộc trò chuyện mới</b><span id="statusText">Sẵn sàng nhận nhiệm vụ</span></div><span id="runtimeBadge" class="badge">ĐANG KIỂM TRA</span></header>
    <section id="content" class="content"><div id="thread" class="thread"><div class="empty"><h2>Giao việc bằng một câu chat</h2><p>Ví dụ: “Kiểm tra dự án, sửa các lỗi an toàn và báo cáo kết quả.”</p><p class="muted">Có thể kéo thả tài liệu vào ô chat. Hệ thống tự chọn AI và công cụ phù hợp.</p></div></div></section>
    <footer class="composer-wrap"><div id="composer" class="composer"><div id="fileChips" class="attachments"></div><div class="input-row"><button id="attach" class="icon" title="Đính kèm tệp">＋</button><input id="fileInput" type="file" multiple class="hidden"><textarea id="message" placeholder="Nhập việc cần làm…" rows="2"></textarea><button id="send" class="send">Gửi</button></div></div><div class="hint">Enter để gửi · Shift+Enter để xuống dòng · Các thao tác nhạy cảm luôn cần phê duyệt</div></footer>
  </main>
</div>
<script>
(function(){
  'use strict';
  var state={conversationId:null,conversations:[],snapshot:null,files:[],sending:false,startupError:'',poll:null,runtimeReady:false};
  var q=function(id){return document.getElementById(id)};
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function fmt(value){try{return new Date(value).toLocaleString('vi-VN')}catch(e){return String(value||'')}}
  async function api(url,options){var response=await fetch(url,Object.assign({credentials:'same-origin',headers:{'content-type':'application/json'}},options||{}));var text=await response.text();var data={};try{data=text?JSON.parse(text):{}}catch(e){data={message:text}}if(!response.ok)throw new Error(data.message||data.error||('HTTP '+response.status));return data}
  function setStartup(show,title,message,error){q('startup').classList.toggle('hidden',!show);q('startupTitle').textContent=title||'';q('startupMessage').textContent=message||'';state.startupError=error||'';q('retryStartup').classList.toggle('hidden',!error);q('copyStartup').classList.toggle('hidden',!error)}
  async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch(e){var area=document.createElement('textarea');area.value=text;document.body.appendChild(area);area.select();var ok=document.execCommand('copy');area.remove();return ok}}
  function failedComponents(bootstrap){var c=bootstrap.components||{};var labels={db:'Cơ sở dữ liệu',redis:'Hàng đợi',evidence:'Kho bằng chứng',adapters:'Hermes/Codex',model:'Mô hình cục bộ',malwareScanner:'Quét tệp'};return Object.keys(labels).filter(function(k){return c[k]!==true}).map(function(k){return labels[k]})}
  function updateRuntime(bootstrap){var p=bootstrap.provider||{};state.runtimeReady=bootstrap.ready===true;q('modelState').textContent='Mô hình: '+(p.managerModel||'chưa rõ')+' · '+(p.ready?'PASS':'CHƯA SẴN SÀNG');q('runtimeBadge').textContent=state.runtimeReady?'SẴN SÀNG':'CHƯA SẴN SÀNG';q('runtimeBadge').className='badge '+(state.runtimeReady?'ok':'bad');q('send').disabled=!state.runtimeReady}
  async function bootstrap(){setStartup(true,'Đang khởi động Workflow AI','Đang kiểm tra toàn bộ mô hình, dữ liệu, hàng đợi và bộ thực thi.','');try{var boot=await api('/v1/chat/bootstrap');updateRuntime(boot);if(!state.runtimeReady){throw new Error('Thành phần chưa sẵn sàng: '+failedComponents(boot).join(', '))}await loadConversations();setStartup(false);startPolling()}catch(e){var report=['WORKFLOW AI V2 — STARTUP ERROR','',new Date().toISOString(),'URL: '+location.href,'Lỗi: '+e.message,'','Hãy phân tích nguyên nhân và hướng dẫn xử lý an toàn.'].join('\n');setStartup(true,'Chưa thể mở Workflow AI','Hệ thống chưa sẵn sàng. Có thể sao chép chẩn đoán để hỏi ChatGPT.',report)}}
  async function loadConversations(){var data=await api('/v1/chat/conversations');state.conversations=data.items||[];if(!state.conversations.length){var created=await api('/v1/chat/conversations',{method:'POST',body:'{}'});state.conversations=[created]}renderConversations();if(!state.conversationId)state.conversationId=state.conversations[0].conversationId;await loadSnapshot()}
  function renderConversations(){q('conversationList').innerHTML=state.conversations.map(function(c){return '<div class="conversation '+(c.conversationId===state.conversationId?'active':'')+'" data-id="'+esc(c.conversationId)+'"><b>'+esc(c.title)+'</b><span>'+esc(c.lastMessage||'Chưa có tin nhắn')+'</span></div>'}).join('');Array.from(document.querySelectorAll('.conversation')).forEach(function(el){el.onclick=async function(){state.conversationId=el.getAttribute('data-id');renderConversations();await loadSnapshot();q('side').classList.remove('open')}})}
  async function newConversation(){var created=await api('/v1/chat/conversations',{method:'POST',body:'{}'});state.conversationId=created.conversationId;await loadConversations()}
  async function loadSnapshot(){if(!state.conversationId)return;var keepBottom=q('content').scrollHeight-q('content').scrollTop-q('content').clientHeight<160;state.snapshot=await api('/v1/chat/conversations/'+encodeURIComponent(state.conversationId));q('currentTitle').textContent=state.snapshot.conversation.title;renderThread();if(keepBottom)q('content').scrollTop=q('content').scrollHeight}
  function messageHtml(m){return '<div class="bubble '+(m.role==='USER'?'user':'assistant')+'">'+esc(m.content)+'<div class="meta">'+fmt(m.createdAt)+'</div></div>'}
  function progressHtml(items){if(!items.length)return '';var groups={};var order=[];items.forEach(function(p){var key=p.taskId||'SYSTEM';if(!groups[key]){groups[key]=[];order.push(key)}groups[key].push(p)});return order.slice(-4).map(function(key,index){var recent=groups[key].slice(-8);return '<div class="card progress"><h3>Tiến độ nhiệm vụ '+(order.length-order.slice(-4).length+index+1)+'</h3>'+recent.map(function(p){return '<div><span class="badge">'+esc(p.stage)+'</span> '+esc(p.message)+' <span class="muted">'+(p.percent==null?'':p.percent+'%')+'</span></div>'}).join('')+'</div>'}).join('')}
  function clarificationSummary(c){return ['WORKFLOW AI V2 — CLARIFICATION QUESTION','',c.question||'',c.reason?'Lý do: '+c.reason:'','','Hãy phân tích bối cảnh và đề xuất câu trả lời phù hợp.'].join('\n')}
  function clarificationHtml(items){return items.filter(function(x){return x.status==='PENDING'}).map(function(c){var opts=(c.options||[]).map(function(o){return '<button class="option clarificationOption" data-id="'+esc(c.clarificationId)+'" data-answer="'+esc(o)+'">'+esc(o)+'</button>'}).join('');return '<div class="card clarification"><h3>Cần anh trả lời</h3><div>'+esc(c.question)+'</div><div class="muted">'+esc(c.reason)+'</div><div class="options">'+opts+'</div><div class="actions"><input class="clarificationInput" data-id="'+esc(c.clarificationId)+'" placeholder="Nhập câu trả lời" style="flex:1;min-width:220px;padding:9px;border:1px solid #cbd5e1;border-radius:9px"><button class="clarificationSend" data-id="'+esc(c.clarificationId)+'">Trả lời</button><button class="ghost askClarification" data-id="'+esc(c.clarificationId)+'">Sao chép để hỏi ChatGPT</button></div></div>'}).join('')}
  function approvalSummary(a){var action=a.action||{};var manager=action.manager||{};var policy=action.policy||{};return (manager.nextAction||'Thao tác được bảo vệ')+(policy.reason?'\nLý do: '+policy.reason:'')}
  function approvalHtml(items){return items.filter(function(x){return x.status==='PENDING'}).map(function(a){return '<div class="card approval"><h3>Chờ phê duyệt</h3><div style="white-space:pre-wrap">'+esc(approvalSummary(a))+'</div><div class="actions"><button class="success approve" data-id="'+esc(a.approvalId)+'">Duyệt</button><button class="danger reject" data-id="'+esc(a.approvalId)+'">Từ chối</button><button class="ghost askApproval" data-id="'+esc(a.approvalId)+'">Sao chép để hỏi ChatGPT</button></div><details class="detail"><summary>Chi tiết kỹ thuật đã giới hạn</summary><pre>'+esc(JSON.stringify(a.action,null,2))+'</pre></details></div>'}).join('')}
  function diagnosticHtml(items){return items.slice(0,5).map(function(d){return '<div class="card diagnostic"><h3>'+esc(d.summary)+'</h3><div class="muted">'+esc(d.errorCode)+' · '+fmt(d.createdAt)+'</div><div class="actions"><button class="copyDiagnostic" data-id="'+esc(d.diagnosticId)+'">Sao chép để hỏi ChatGPT</button></div><details class="detail"><summary>Xem chẩn đoán kỹ thuật đã che bí mật</summary><pre>'+esc(d.reportText)+'</pre></details></div>'}).join('')}
  function renderThread(){var s=state.snapshot;if(!s)return;var html='';html+=(s.messages||[]).map(messageHtml).join('');html+=clarificationHtml(s.clarifications||[]);html+=approvalHtml(s.approvals||[]);html+=progressHtml(s.progress||[]);html+=diagnosticHtml(s.diagnostics||[]);if(!html)html='<div class="empty"><h2>Giao việc bằng một câu chat</h2><p>Hệ thống tự chọn AI, phạm vi và công cụ phù hợp.</p></div>';q('thread').innerHTML=html;bindDynamic();var active=(s.progress||[]).slice(-1)[0];q('statusText').textContent=active?active.message:'Sẵn sàng nhận nhiệm vụ'}
  function bindDynamic(){Array.from(document.querySelectorAll('.clarificationOption')).forEach(function(b){b.onclick=function(){answerClarification(b.getAttribute('data-id'),b.getAttribute('data-answer'))}});Array.from(document.querySelectorAll('.clarificationSend')).forEach(function(b){b.onclick=function(){var id=b.getAttribute('data-id');var input=document.querySelector('.clarificationInput[data-id="'+id+'"]');answerClarification(id,input&&input.value)}});Array.from(document.querySelectorAll('.askClarification')).forEach(function(b){b.onclick=function(){var c=(state.snapshot.clarifications||[]).find(function(x){return x.clarificationId===b.getAttribute('data-id')});if(c)copyText(clarificationSummary(c))}});Array.from(document.querySelectorAll('.approve')).forEach(function(b){b.onclick=function(){decideApproval(b.getAttribute('data-id'),'APPROVED')}});Array.from(document.querySelectorAll('.reject')).forEach(function(b){b.onclick=function(){decideApproval(b.getAttribute('data-id'),'REJECTED')}});Array.from(document.querySelectorAll('.askApproval')).forEach(function(b){b.onclick=function(){var a=(state.snapshot.approvals||[]).find(function(x){return x.approvalId===b.getAttribute('data-id')});copyText(['WORKFLOW AI V2 — APPROVAL QUESTION','',approvalSummary(a||{}),'','Hãy phân tích rủi ro và cho tôi ý kiến có nên duyệt hay không.'].join('\n'))}});Array.from(document.querySelectorAll('.copyDiagnostic')).forEach(function(b){b.onclick=function(){var d=(state.snapshot.diagnostics||[]).find(function(x){return x.diagnosticId===b.getAttribute('data-id')});if(d)copyText(d.reportText)}})}
  async function answerClarification(id,answer){if(!answer||!String(answer).trim())return;await api('/v1/chat/conversations/'+encodeURIComponent(state.conversationId)+'/clarifications/'+encodeURIComponent(id),{method:'POST',body:JSON.stringify({answer:String(answer).trim()})});await loadSnapshot()}
  async function decideApproval(id,decision){await api('/v1/chat/conversations/'+encodeURIComponent(state.conversationId)+'/approvals/'+encodeURIComponent(id),{method:'POST',body:JSON.stringify({decision:decision})});await loadSnapshot()}
  function renderFiles(){q('fileChips').innerHTML=state.files.map(function(f,i){return '<span class="file-chip">'+esc(f.name)+' <b data-index="'+i+'" class="removeFile" style="cursor:pointer">×</b></span>'}).join('');Array.from(document.querySelectorAll('.removeFile')).forEach(function(x){x.onclick=function(){state.files.splice(Number(x.getAttribute('data-index')),1);renderFiles()}})}
  function addFiles(list){Array.from(list||[]).forEach(function(file){if(state.files.length<20)state.files.push(file)});renderFiles()}
  function fileBase64(file){return new Promise(function(resolve,reject){var reader=new FileReader();reader.onload=function(){var value=String(reader.result||'');resolve(value.slice(value.indexOf(',')+1))};reader.onerror=function(){reject(reader.error||new Error('Không đọc được tệp'))};reader.readAsDataURL(file)})}
  async function uploadFiles(){var ids=[];for(var i=0;i<state.files.length;i+=1){q('statusText').textContent='Đang tải tệp '+(i+1)+'/'+state.files.length;var file=state.files[i];var contentBase64=await fileBase64(file);var result=await api('/v1/chat/conversations/'+encodeURIComponent(state.conversationId)+'/attachments',{method:'POST',body:JSON.stringify({fileName:file.name,mediaType:file.type||'application/octet-stream',contentBase64:contentBase64})});ids.push(result.attachment.attachmentId)}return ids}
  async function send(){var content=q('message').value.trim();if(!content||state.sending||!state.runtimeReady)return;state.sending=true;q('send').disabled=true;try{var attachmentIds=await uploadFiles();await api('/v1/chat/conversations/'+encodeURIComponent(state.conversationId)+'/messages',{method:'POST',body:JSON.stringify({content:content,attachmentIds:attachmentIds,clientMessageId:'WEB-'+Date.now()+'-'+Math.random().toString(16).slice(2)})});q('message').value='';state.files=[];renderFiles();await loadConversations()}catch(e){var report=['WORKFLOW AI V2 — CHAT SUBMISSION ERROR','',new Date().toISOString(),'Conversation: '+state.conversationId,'Lỗi: '+e.message,'','Hãy phân tích và hướng dẫn xử lý an toàn.'].join('\n');await copyText(report);alert('Không gửi được nhiệm vụ. Chẩn đoán đã được sao chép để dán vào ChatGPT.')}finally{state.sending=false;q('send').disabled=!state.runtimeReady}}
  function startPolling(){if(state.poll)clearInterval(state.poll);state.poll=setInterval(function(){loadSnapshot().catch(function(){})},2000)}
  q('newConversation').onclick=function(){newConversation().catch(function(e){alert(e.message)})};q('retryStartup').onclick=bootstrap;q('copyStartup').onclick=function(){copyText(state.startupError)};q('attach').onclick=function(){q('fileInput').click()};q('fileInput').onchange=function(){addFiles(q('fileInput').files);q('fileInput').value=''};q('send').onclick=send;q('message').onkeydown=function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};q('menu').onclick=function(){q('side').classList.toggle('open')};['dragenter','dragover'].forEach(function(name){q('composer').addEventListener(name,function(e){e.preventDefault();q('composer').classList.add('drag')})});['dragleave','drop'].forEach(function(name){q('composer').addEventListener(name,function(e){e.preventDefault();q('composer').classList.remove('drag');if(name==='drop')addFiles(e.dataTransfer.files)})});bootstrap();
})();
</script>
</body>
</html>`;
